{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Sample Application Flow OAuth2 Project",
    "description" : "This is an example of using OAuth2 Application Flow in a specification to describe security to your API.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/Computewell/Task-Manager/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "security" : [ {
    "application" : [ "read", "write" ]
  } ],
  "components" : {
    "schemas" : { },
    "securitySchemes" : {
      "application" : {
        "type" : "oauth2",
        "flows" : {
          "clientCredentials" : {
            "tokenUrl" : "http://example.com/oauth/token",
            "scopes" : {
              "write" : "allows modifying resources",
              "read" : "allows reading resources"
            }
          }
        }
      }
    }
  }
}